version: '3.7'

services:
  app:
    build:
      context: .
      target: production
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - .:/src/app
    depends_on:
      - db

  db:
    image: "postgres:12"
    restart: always
    ports:
      - "7557:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DB_HOST}
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:
    driver: local